hmrc/api-hub-applications

app/uk/gov/hmrc/apihubapplications/config/AppConfig.scala, app/uk/gov/hmrc/apihubapplications/config/Module.scala, app/uk/gov/hmrc/apihubapplications/controllers/MicroserviceHelloWorldController.scala, conf/application.conf, it/uk/gov/hmrc/apihubapplications/HealthEndpointIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/MicroserviceHelloWorldControllerSpec.scala
Let the sbt plugin add all the copyright headers
=> HIPP-182: Add copyright notices

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, conf/app.routes, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-224
=> HIPP-224: Implement endpoint to return details of a single application

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, build.sbt, conf/app.routes, project/plugins.sbt, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-285
=> HIPP-285: Update to "Register application" in the backend

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, conf/app.routes, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-287
=> HIPP-287: Add pending scopes endpoint

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/applications/ApplicationLensesSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-36
=> HIPP-36: Automatically add creator of the application as a team member

app/uk/gov/hmrc/apihubapplications/models/application/Application.scala, app/uk/gov/hmrc/apihubapplications/models/application/NewApplication.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/ApplicationGenerator.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/applications/ApplicationLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepositorySpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-404
=> HIPP-404: Update Register application endpoint

app/uk/gov/hmrc/apihubapplications/config/Module.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/models/idms/Client.scala, app/uk/gov/hmrc/apihubapplications/models/idms/ClientResponse.scala, app/uk/gov/hmrc/apihubapplications/models/idms/IdmsException.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/application.conf, docs/openapi.yaml, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/FakeIdmsConnector.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/applications/ApplicationLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-473
=> HIPP-473: Change api-hub-applications register application endpoint to create secondary credentials

app/uk/gov/hmrc/apihubapplications/controllers/ConnectivityTestController.scala, conf/app.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-530
=> HIPP-530: Create test endpoint for HIP API Platform to call MDTP

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/idms/ClientResponse.scala, app/uk/gov/hmrc/apihubapplications/models/idms/IdmsException.scala, app/uk/gov/hmrc/apihubapplications/models/idms/Secret.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/FakeIdmsConnector.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-475
=> HIPP-475: Retrieve secondary credentials

app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-507
=> HIPP-507: Register application endpoint to create primary clientID

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/models/idms/ClientScope.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/Helpers.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/FakeIdmsConnector.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/HelpersSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-504
=> HIPP-504:  Make request to IDMS to retrieve scopes

app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-506
=> HIPP-506: Make request to IDMS to retrieve scopes

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, conf/application.conf, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-545
=> HIPP-545: api-hub-applications to call IDMS stub with dummy clientId/ secret

build.sbt
See https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=176632503
=> HIPP-545: Try and stabilise build

app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-590
=> HIPP-590: Approving a scope returning 404

conf/application.conf, project/AppDependencies.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-469
=> HIPP-469: Upgrade dependencies

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-555
=> HIPP-555: Implement optional proxy when connecting to secondary IDMS

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, conf/application.conf, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-553
=> HIPP-553: Add api-key header when making requests to the secondary environment

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApplicationDataIssueException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApplicationNotFoundException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApplicationsException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/IdmsException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/NotUpdatedException.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/Helpers.scala, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/FakeIdmsConnector.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/HelpersSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-584
Rationalise the exception hierarchy and how exceptions are raised
=> HIPP-584: rationalise exceptions

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-584
Also applied ExceptionRaising to IdmsConnectorImpl to standardise exception behaviour
=> HIPP-584: Refactor return types in database layer in api-hub-applications

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApplicationDataIssueException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-583
=> HIPP-583: Refactor error representation and handling in api-hub-applications

app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/IdmsException.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, conf/app.routes, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/FakeIdmsConnector.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/applications/ApplicationLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/HelpersSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-604
=> HIPP-604: Create backend delete application endpoint

app/uk/gov/hmrc/apihubapplications/models/application/Application.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/models/application/Issues.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, test/uk/gov/hmrc/apihubapplications/models/applications/ApplicationLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepositorySpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-615
=> HIPP-615: Return errors from application by ID endpoint

app/uk/gov/hmrc/apihubapplications/controllers/TestConnectivityController.scala, conf/app.routes, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-591
=> HIPP-591: Move test connectivity endpoint

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-634
=> HIPP-634: Add enrich parameter to backend endpoint

conf/application.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-633
=> HIPP-633: Change local port that identity-management-service-stubs runs on

app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala
This reverts commit 2892bce0dcddcf45b5dd434706cb733b27637747.
=> Revert "HIPP-659: Test mdc logging (#67)"

app/uk/gov/hmrc/apihubapplications/config/CryptoProviderModule.scala, app/uk/gov/hmrc/apihubapplications/crypto/NoCrypto.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/SensitiveApplication.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/SensitiveCreator.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/SensitiveTeamMember.scala, conf/application.conf, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, project/AppDependencies.scala, test/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepositorySpec.scala
Field level encryption of emails
=> HIPP-740: Field level encryption

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/NewScope.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, project/plugins.sbt, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/applications/NewScopeSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-767
=> HIPP-767: Add an API - Complete the Journey

app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/models/application/Credential.scala, app/uk/gov/hmrc/apihubapplications/models/idms/ClientResponse.scala, app/uk/gov/hmrc/apihubapplications/models/idms/Secret.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/encrypted/SensitiveApplication.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/encrypted/SensitiveCreator.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/encrypted/SensitiveTeamMember.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/unencrypted/DbApplication.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/unencrypted/DbCredential.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/unencrypted/DbEnvironment.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/unencrypted/DbEnvironments.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/unencrypted/DbModel.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricher.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/ApplicationGenerator.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/ApplicationTestLenses.scala, test/uk/gov/hmrc/apihubapplications/models/applications/ApplicationLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepositorySpec.scala, test/uk/gov/hmrc/apihubapplications/repositories/models/unencrypted/DbApplicationSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ApplicationEnricherSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-829
=> HIPP-829: Support multiple credentials - backend

app/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsController.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestStatus.scala, app/uk/gov/hmrc/apihubapplications/repositories/AccessRequestsRepository.scala, app/uk/gov/hmrc/apihubapplications/repositories/RepositoryHelpers.scala, app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala, build.sbt, conf/app.routes, it/uk/gov/hmrc/apihubapplications/AccessRequestsRepositoryIntegrationSpec.scala, project/plugins.sbt, test/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestStatusSpec.scala, test/uk/gov/hmrc/apihubapplications/services/AccessRequestsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-865
=> HIPP-865: API Production Access Requests page

app/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsController.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestDecisionRequest.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestLenses.scala, app/uk/gov/hmrc/apihubapplications/models/exception/AccessRequestNotFoundException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/AccessRequestStatusInvalidException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/repositories/AccessRequestsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, it/uk/gov/hmrc/apihubapplications/AccessRequestsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/AccessRequestsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-878
=> HIPP-878: Approve production access request

app/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsController.scala, app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala, conf/app.routes, test/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/AccessRequestsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-876
=> HIPP-876: Reject production access request

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApplicationCredentialLimitException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/CredentialNotFoundException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-586
=> HIPP-586: Delete credentials

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, it/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-909
=> HIPP-909: Add endpoints

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/TeamMemberExistsException.scala, app/uk/gov/hmrc/apihubapplications/models/requests/TeamMemberRequest.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, project/plugins.sbt, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-396
=> HIPP-396: Create backend endpoint to add team member

app/uk/gov/hmrc/apihubapplications/connectors/SimpleApiDeploymentConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/SimpleApiDeploymentConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/SimpleApiDeploymentException.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/GenerateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/GenerateRequest.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/GenerateResponse.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/Responses.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/ValidationFailure.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/ValidationFailuresResponse.scala, it/test/uk/gov/hmrc/apihubapplications/SimpleApiDeploymentConnectorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1015
=> HIPP-1015: Create a Simple API Deployment connector

app/uk/gov/hmrc/apihubapplications/controllers/DeployApiController.scala, app/uk/gov/hmrc/apihubapplications/models/simpleapideployment/Responses.scala, conf/application.conf, test/uk/gov/hmrc/apihubapplications/controllers/DeployApiControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1029
=> HIPP-1029: Create API form

app/uk/gov/hmrc/apihubapplications/connectors/SimpleApiDeploymentConnectorImpl.scala
Add some logging for 400 responses to see if we get something other than ValidationFailuresResponse
=> HIPP-1029: Response diagnostics

app/uk/gov/hmrc/apihubapplications/controllers/TeamsController.scala, app/uk/gov/hmrc/apihubapplications/models/team/Team.scala, app/uk/gov/hmrc/apihubapplications/models/team/TeamLenses.scala, app/uk/gov/hmrc/apihubapplications/repositories/TeamsRepository.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/team/encrypted/SensitiveTeam.scala, app/uk/gov/hmrc/apihubapplications/services/TeamsService.scala, it/test/uk/gov/hmrc/apihubapplications/TeamsRepositoryIntegrationSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1049
=> HIPP-1049: Add a Teams repository

app/uk/gov/hmrc/apihubapplications/controllers/TeamsController.scala, app/uk/gov/hmrc/apihubapplications/models/team/NewTeam.scala, app/uk/gov/hmrc/apihubapplications/models/team/Team.scala, conf/app.routes, test/uk/gov/hmrc/apihubapplications/controllers/TeamsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/TeamsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1051
=> HIPP-1051: Create team endpoint

app/uk/gov/hmrc/apihubapplications/controllers/TeamsController.scala, app/uk/gov/hmrc/apihubapplications/repositories/TeamsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/TeamsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/TeamsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/TeamsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/TeamsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1050
=> HIPP-1050: Add endpoint to retrieve teams

app/uk/gov/hmrc/apihubapplications/controllers/TeamsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/NotUpdatedException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/TeamMemberExistsException.scala, app/uk/gov/hmrc/apihubapplications/repositories/TeamsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/TeamsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/TeamsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/TeamsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/TeamsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1053
=> HIPP-1053: Add an endpoint to add members to a team

app/uk/gov/hmrc/apihubapplications/config/Module.scala
…lues even when running locally
=> HIPP-1136 force use of UTC 

app/uk/gov/hmrc/apihubapplications/config/AppConfig.scala, app/uk/gov/hmrc/apihubapplications/config/InternalAuthTokenInitialiser.scala, app/uk/gov/hmrc/apihubapplications/config/Module.scala, app/uk/gov/hmrc/apihubapplications/connectors/IntegrationCatalogueConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IntegrationCatalogueConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala, app/uk/gov/hmrc/apihubapplications/models/api/ApiTeam.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentsRequest.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/IntegrationCatalogueException.scala, app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala, conf/application.conf, it/test/resources/application.conf, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, it/test/uk/gov/hmrc/apihubapplications/IntegrationCatalogueConnectorSpec.scala, it/test/uk/gov/hmrc/apihubapplications/InternalAuthTokenInitialiserSpec.scala, test/resources/application.conf, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1156
=> HIPP-1156: Add teams to the form

app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/models/apim/CreateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentsRequest.scala, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1145
=> HIPP-1145: Include passthrough checkbox in Simple API Basic form

app/uk/gov/hmrc/apihubapplications/controllers/TeamsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/TeamNameNotUniqueException.scala, app/uk/gov/hmrc/apihubapplications/repositories/TeamsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/TeamsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/TeamsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/TeamsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/TeamsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1203
=> HIPP-1203: Validate team name for uniqueness

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/ApplicationLenses.scala, app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1206
=> HIPP-1206: View deleted applications

app/uk/gov/hmrc/apihubapplications/connectors/APIMConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala, app/uk/gov/hmrc/apihubapplications/models/apim/RedeploymentRequest.scala, app/uk/gov/hmrc/apihubapplications/models/apim/UpdateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApimException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1119
=> HIPP-1119: Update a simple API

app/uk/gov/hmrc/apihubapplications/models/apim/CreateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentsRequest.scala, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1402
=> HIPP-1402: Add egressPrefix & prefixesToRemove

app/uk/gov/hmrc/apihubapplications/connectors/APIMConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala, app/uk/gov/hmrc/apihubapplications/models/apim/CreateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentDetails.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DetailsResponse.scala, app/uk/gov/hmrc/apihubapplications/models/apim/RedeploymentRequest.scala, app/uk/gov/hmrc/apihubapplications/models/apim/UpdateMetadata.scala, app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1429
=> HIPP-1429: Add egressPrefix & prefixesToRemove fields to Update form

app/uk/gov/hmrc/apihubapplications/repositories/ApplicationsRepository.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsLifecycleService.scala, it/test/uk/gov/hmrc/apihubapplications/ApplicationsIntegrationSpec.scala, it/test/uk/gov/hmrc/apihubapplications/ApplicationsRepositoryIntegrationSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsLifecycleServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1443
=> HIPP-1443: Hard delete applications without access requests

app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/models/apim/CreateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DetailsResponse.scala, app/uk/gov/hmrc/apihubapplications/models/apim/UpdateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApimException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApplicationsException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/exception/IdmsException.scala, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, it/test/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1402
Fix case issue. OAS specification has new fields in lower case but APIM implementation uses camel-case.
Also add more logging when unexpected responses are returned by either IDMS or APIM.
=> HIPP-1402: Fix case issue

app/uk/gov/hmrc/apihubapplications/services/helpers/ScopeFixer.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ScopeFixerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1301
=> HIPP-1301: Handling missing APIs

app/uk/gov/hmrc/apihubapplications/connectors/APIMConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/connectors/IntegrationCatalogueConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IntegrationCatalogueConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/StatsController.scala, app/uk/gov/hmrc/apihubapplications/models/api/IntegrationResponse.scala, app/uk/gov/hmrc/apihubapplications/models/apim/ApiDeployment.scala, app/uk/gov/hmrc/apihubapplications/models/stats/ApisInProductionStatistic.scala, app/uk/gov/hmrc/apihubapplications/services/StatsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, it/test/uk/gov/hmrc/apihubapplications/IntegrationCatalogueConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/StatsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/StatsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1541
=> HIPP-1541: Display the no. of APIs deployed in prod

app/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsController.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequest.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestCancelRequest.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestCancelled.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestLenses.scala, app/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestRequest.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/accessRequest/encrypted/SensitiveAccessRequest.scala, app/uk/gov/hmrc/apihubapplications/repositories/models/accessRequest/encrypted/SensitiveAccessRequestCancelled.scala, app/uk/gov/hmrc/apihubapplications/services/AccessRequestsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/EmailConnectorSpec.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/AccessRequestGenerator.scala, test/uk/gov/hmrc/apihubapplications/controllers/AccessRequestsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/StatsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/accessRequest/AccessRequestCancelRequestSpec.scala, test/uk/gov/hmrc/apihubapplications/services/AccessRequestsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsLifecycleServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1550
=> HIPP-1550: Cancel a pending production access request

app/uk/gov/hmrc/apihubapplications/controllers/StatsController.scala, app/uk/gov/hmrc/apihubapplications/services/StatsService.scala, conf/app.routes, test-common/uk/gov/hmrc/apihubapplications/testhelpers/ApiDetailGenerators.scala, test/uk/gov/hmrc/apihubapplications/controllers/StatsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/StatsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1610
=> HIPP-1610: List of APIs in production stat

app/uk/gov/hmrc/apihubapplications/controllers/StatsController.scala, app/uk/gov/hmrc/apihubapplications/models/api/ApiDetail.scala, app/uk/gov/hmrc/apihubapplications/models/api/ApiDetailSummary.scala, app/uk/gov/hmrc/apihubapplications/services/StatsService.scala, test-common/uk/gov/hmrc/apihubapplications/testhelpers/ApiDetailGenerators.scala, test/uk/gov/hmrc/apihubapplications/controllers/StatsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/api/ApiDetailLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/services/StatsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ScopeFixerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1610
Make the return type ApiDetailSummary not ApiDetail
=> HIPP-1610: Use ApiDetailSummary

app/uk/gov/hmrc/apihubapplications/models/exception/IdmsException.scala, it/test/uk/gov/hmrc/apihubapplications/IdmsConnectorSpec.scala
This change is required so alerts can be raised on said custom log line.
=> HIPP-1626: Handle 401/403 status codes with custom logs

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/CredentialScopes.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsCredentialsService.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsCredentialsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1628
=> HIPP-1628: Diagnostic scope view

app/uk/gov/hmrc/apihubapplications/config/HipEnvironments.scala, app/uk/gov/hmrc/apihubapplications/config/Module.scala, app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorParityImpl.scala, app/uk/gov/hmrc/apihubapplications/connectors/IdmsConnectorParityImpl.scala, app/uk/gov/hmrc/apihubapplications/connectors/ProxySupport.scala, app/uk/gov/hmrc/apihubapplications/controllers/EnvironmentParityTestController.scala, conf/app.routes, conf/application.conf, conf/hipEnvironments.conf, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorParityImplSpec.scala, it/test/uk/gov/hmrc/apihubapplications/IdmsConnectorParityImplSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1667
=> HIPP-1670: Add environment parity connectors

app/uk/gov/hmrc/apihubapplications/services/ApplicationsApiService.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, app/uk/gov/hmrc/apihubapplications/services/helpers/ScopeFixer.scala, project/plugins.sbt, test-common/uk/gov/hmrc/apihubapplications/testhelpers/FakeHipEnvironments.scala, test/uk/gov/hmrc/apihubapplications/services/AccessRequestsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsApiServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsCredentialsServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/helpers/ScopeFixerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1692
Also changed the return type of scope fixer from Right[Application] to Right[Unit]. There was some "enrichment" going on that isn't needed as the returned value was ignored.
=> HIPP-1692: Configurable environments - ScopeFixer

app/uk/gov/hmrc/apihubapplications/mongojobs/DeleteAllApplicationsJob.scala, test/uk/gov/hmrc/apihubapplications/mongojobs/DeleteAllApplicationsJobSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1688
=> HIPP-1688: Delete all applications job

app/uk/gov/hmrc/apihubapplications/controllers/ApplicationsController.scala, app/uk/gov/hmrc/apihubapplications/models/application/Credential.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsCredentialsService.scala, app/uk/gov/hmrc/apihubapplications/services/ApplicationsService.scala, conf/app.routes, test/uk/gov/hmrc/apihubapplications/controllers/ApplicationsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsCredentialsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1754
=> HIPP-1754: Get credentials

app/uk/gov/hmrc/apihubapplications/controllers/EnvironmentParityTestController.scala, conf/app.routes
https://jira.tools.tax.service.gov.uk/browse/HIPP-1788
=> HIPP-1788: Broken environment parity test page

app/uk/gov/hmrc/apihubapplications/config/HipEnvironments.scala, app/uk/gov/hmrc/apihubapplications/mongojobs/EnvironmentParityDataMigrationJob.scala, test/uk/gov/hmrc/apihubapplications/mongojobs/EnvironmentParityDataMigrationJobSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1791
=> HIPP-1791: Data migration step 3 - database transform

app/uk/gov/hmrc/apihubapplications/config/Module.scala, app/uk/gov/hmrc/apihubapplications/connectors/AutopublishConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/AutopublishConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/AutopublishException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala, conf/app.routes, conf/application.conf, it/test/uk/gov/hmrc/apihubapplications/AutopublishConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1886
=> HIPP-1886: Add endpoint to force-publish an API

app/uk/gov/hmrc/apihubapplications/mongojobs/DeletePreProductionCredentialsJob.scala, conf/application.conf, test/uk/gov/hmrc/apihubapplications/mongojobs/DeletePreProductionCredentialsJobSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1943
=> HIPP-1943: Delete pre-production credentials

app/uk/gov/hmrc/apihubapplications/config/HipEnvironments.scala, conf/hipEnvironments.conf, test/uk/gov/hmrc/apihubapplications/config/HipEnvironmentsSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1957
=> HIPP-1957: Add flag to disable HIP environments

app/uk/gov/hmrc/apihubapplications/connectors/APIMConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/APIMConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/ApimController.scala, app/uk/gov/hmrc/apihubapplications/models/apim/Responses.scala, app/uk/gov/hmrc/apihubapplications/models/apim/StatusResponse.scala, app/uk/gov/hmrc/apihubapplications/scheduler/ApimSyntheticMonitoringScheduler.scala, app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala, conf/app.routes, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/ApimControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/scheduler/ApimSyntheticMonitoringSchedulerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-1968
=> HIPP-1968: Add missing APIM endpoints

app/uk/gov/hmrc/apihubapplications/models/apim/CreateMetadata.scala, app/uk/gov/hmrc/apihubapplications/models/apim/DeploymentsRequest.scala, app/uk/gov/hmrc/apihubapplications/models/apim/RedeploymentRequest.scala, app/uk/gov/hmrc/apihubapplications/models/apim/UpdateMetadata.scala, it/test/uk/gov/hmrc/apihubapplications/APIMConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-2095
https://jira.tools.tax.service.gov.uk/browse/HIPP-2096
=> HIPP-2095: Add BasePath to APIM calls

app/uk/gov/hmrc/apihubapplications/controllers/TeamsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/EgressNotFoundException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/models/team/TeamLenses.scala, app/uk/gov/hmrc/apihubapplications/services/TeamsService.scala, conf/app.routes, test/uk/gov/hmrc/apihubapplications/controllers/TeamsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/models/team/TeamLensesSpec.scala, test/uk/gov/hmrc/apihubapplications/services/TeamsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-2125
=> HIPP-2125: Remove an egress from a Team

conf/application.conf
https://jira.tools.tax.service.gov.uk/browse/HIPP-2211
=> HIPP-2211: Turn events on in the local environment

app/uk/gov/hmrc/apihubapplications/connectors/IntegrationCatalogueConnector.scala, app/uk/gov/hmrc/apihubapplications/connectors/IntegrationCatalogueConnectorImpl.scala, app/uk/gov/hmrc/apihubapplications/controllers/DeploymentsController.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ApiNotFoundException.scala, app/uk/gov/hmrc/apihubapplications/models/exception/ExceptionRaising.scala, app/uk/gov/hmrc/apihubapplications/services/ApiEventService.scala, app/uk/gov/hmrc/apihubapplications/services/DeploymentsService.scala, app/uk/gov/hmrc/apihubapplications/utility/OasHelpers.scala, it/test/uk/gov/hmrc/apihubapplications/IntegrationCatalogueConnectorSpec.scala, test/uk/gov/hmrc/apihubapplications/controllers/DeploymentsControllerSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApiEventServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/ApplicationsEventServiceSpec.scala, test/uk/gov/hmrc/apihubapplications/services/DeploymentsServiceSpec.scala
https://jira.tools.tax.service.gov.uk/browse/HIPP-2172
=> HIPP-2172: API events
